services:
  pingvin-share:
    image: ghcr.io/blakehonda99/vargr-share
    restart: unless-stopped
    ports:
      - 4300:4300
    environment:
      - TRUST_PROXY=false # Set to true if a reverse proxy is in front of the container
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"

  # To add ClamAV, to scan your shares for malicious files, 
  # see https://stonith404.github.io/pingvin-share/setup/integrations/#clamav-docker-only
